#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/
require_once __DIR__ . '/vendor/autoload.php';

if (($_SERVER['argv'][1] ?? '') === 'autowiring:cache') {
    \MacropaySolutions\Kernel\Container\BoundMethod::enableClassesFqnsToCacheForAutowire();
}

$app = require __DIR__ . '/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Console Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(
    'MacropaySolutions\Kernel\Contracts\Console\Kernel'
);

exit($kernel->handle(new ArgvInput(), new ConsoleOutput()));
